In [1]:
print("hello numpy")

hello numpy


### NumPy重要功能如下:
- 1. 高性能科学计算和数据分析的基础包
- 2. ndarray , 多维数组 , 具有矢量运算能力 , 快速 , 节省空间
- 3. 矩阵运算 , 无需循环 , 可完成类似 Matlab 的矩阵运算
- 4. 用于读写磁盘数据的工具以及操作内存映射文件的工具

### NumPy 的数组类被称为 ndarray , 通常被称为数组
- ##### ndarray对象属性有:  
    - 1. ndarray.ndim : 数组的轴(维度)数
    - 2. ndarray.shape : 数组的维度
    - 3. ndarray.size : 数组元素的总个数
    - 4. ndarray.dtype : 数组元素的类型
    - 5. ndarray.itemsize : 数组中每个元素的字节大小
    - 6. ndarray.nbytes : 数组占用的字节数
##### 数组的维度: 这是一个指示数组在每个维度上大小的整数元组.
- 例如: 一个矩阵的维度为 (m,n) , 表示它是一个 m 行 n 列的矩阵

In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)               # 生成一个从 0 到 14 的数组 , 并将其转换为一个 3 行 5 列的二维数组
print("数组的维度:" , a.shape)                  # 输出数组 a 的维度
print("数组的元素类型:" , a.dtype)                # 输出数组 a 的元素类型
print("数组的每个元素字节大小:" , a.itemsize)                # 输出数组 a 中每个元素的字节大小
print("数组占用的字节数:" , a.nbytes)                # 输出数组 a 占用的字节数
print("数组的元素总个数:" , a.size)                # 输出数组 a 的元素总个数
print("数组的轴(维度)数:" , a.ndim)                # 输出数组 a 的轴(维度)数
print("数组a:" , a)

数组的维度: (3, 5)
数组的元素类型: int32
数组的每个元素字节大小: 4
数组占用的字节数: 60
数组的元素总个数: 15
数组的轴(维度)数: 2
数组a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
# 创建一个数组
b = np.array([1,2,3,4,5])
print("数组b:" , b)
print("数组b类型:" , type(b))

数组b: [1 2 3 4 5]
数组b类型: <class 'numpy.ndarray'>


In [4]:
# 创建随机矩阵
# 生成指定维度大小(3行4列) 的随机多维浮点型数据(二维) , rand 固定区间为 0.0 ~ 1.0
arr = np.random.rand(3 , 4)
print(arr)
print(type(arr))
print("-----------------------------------------------------------")

# 生成指定维度大小(3行4列) 的随机多维整型数据(二维) , randint() 可指定区间(-1 , 5)
arr = np.random.randint(-1 , 5 , size = (3 ,4))
print(arr)
print(type(arr))
print("-----------------------------------------------------------")

# 生成指定维度大小(3行4列) 的随机多维浮点型数据(二维) , uniform() 可指定区间(-1.0 , 5.0) 产生 -1 到 5 之间的均匀分布的随机数
arr = np.random.uniform(-1.0 , 5.0 , size = (3 ,4))
print(arr)
print(type(arr))
print("-----------------------------------------------------------")


[[0.14120159 0.5929138  0.78693959 0.28920193]
 [0.61678795 0.81954822 0.97523058 0.025159  ]
 [0.95511287 0.40527425 0.68825725 0.73304399]]
<class 'numpy.ndarray'>
-----------------------------------------------------------
[[ 1  0  3  1]
 [ 2  4  2  1]
 [ 4  1 -1  4]]
<class 'numpy.ndarray'>
-----------------------------------------------------------
[[ 4.99400927 -0.07717975  3.35520938  4.56278184]
 [ 2.8620854   4.40606269  0.63641884  4.53692022]
 [ 4.69333159  2.96116135  1.522496   -0.34425102]]
<class 'numpy.ndarray'>
-----------------------------------------------------------


### 创建NumPy的ndarray对象
- array() 函数 , 把 Python 列表 -> ndarray对象

In [5]:
# 1. 创建python列表对象
my_list = [[1 , 2 , 3],
           [4 , 5 , 6],
           [7 , 8 , 9]]
arr = np.array(my_list)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### arange() 函数 , 创建 ndarray对象
- arange(起始 , 结束 , 步长 , dtype = 类型) , 类似于 range() 函数 , 但返回的是 ndarray 对象

In [6]:
arr = np.arange(0 , 15 , 3 , dtype=int)
print(arr)
print(f"元素的类型为{arr.dtype}")
print("-------------------------------")
arr = np.arange(15).reshape(3 , 5)
print(arr)

[ 0  3  6  9 12]
元素的类型为int32
-------------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### numpy 的类型转换 astype()

In [7]:
arr1 = np.arange(0 , 10 , 2 , dtype = np.int64)
print(arr1)
arr2 = arr1.astype(np.float32)
print(arr2)
print(arr2.dtype)


[0 2 4 6 8]
[0. 2. 4. 6. 8.]
float32
