### 等比数列
- np.logspace(start , stop , num , base , dtype)
    - start : 序列的起始值 , 默认值为 0
    - stop : 序列的结束值
    - num : 要生成的样本数量 , 默认值为 50
    - base : 对数空间的底数 , 默认值为 10
    - dtype : 输出数组的数据类型 , 默认值为 None

In [1]:
# 导包
import numpy as np

a = np.logspace(0 , 0 , 10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
b = np.logspace(0 , 2 , 3 , base=3 , dtype = int)
b

array([1, 3, 9])

In [18]:
c = np.logspace(0 , 9 , 10 , base=2 , dtype=int)
c

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

### 等差数列
- np.linspace(start , stop , num , endpoint , dtype)
    - start : 序列的起始值
    - stop : 序列的结束值
    - num : 要生成的样本数量 , 默认值为 50
    - endpoint : 如果为 True , 则 stop 是序列的最后一个值 , 默认值为 True
    - dtype : 输出数组的数据类型 , 默认值为 None

In [28]:
a = np.linspace(1 , 10 , 10 , True , dtype=int)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.arange(0 , 50 , 2)                   # 生成 0 到 48 的偶数 , arange() 也可以用作等差数列
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])