### Numpy内置函数
- ##### 1. 基本函数
    - np.ceil(): 向上最接近的整数 , 参数是 number 或 ndarray对象
    - np.floor(): 向下最接近的整数 , 参数是 number 或 ndarray对象
    - np.rint(): 四舍五入到最近的整数 , 参数是 number 或 ndarray对象    
    - np.isnan(): 判断是否为 NaN(Not a Number) 值 , 参数是 number 或 ndarray对象
    - np.multiply(): 数组元素相乘 , 参数是 number 或 ndarray对象
    - np.divide(): 数组元素相除 , 参数是 number 或 ndarray对象
    - np.abs(): 数组元素的绝对值 , 参数是 number 或 ndarray对象
    - np.where(condition , x , y): 根据条件返回对应值 , 参数是 condition(条件) , x(满足条件时的值) , y(不满足条件时的值)


In [ ]:
import numpy as np

# 向上最接近的整数
a = 3.1
b = np.ceil(a)
b

4.0

In [4]:
a = np.array([1.2,2.3,3.4,4.5,5.6])
b = np.ceil(a)
print(b)
b = np.floor(a)
print(b)

[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]


In [8]:
# multiply() 函数是对应元素相乘 , 要求两个数组的形状相同 , 而不是矩阵相乘
a = np.arange(15).reshape(3,5)
b = np.arange(5,20).reshape(3,5)
c = np.multiply(a,b)
c

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126],
       [150, 176, 204, 234, 266]])

In [9]:
print(np.where(a > 0 , 1 , -1))

[[-1  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]
