In [2]:
import numpy as np

# Numpy 运算

##### 1 基本运算
- 数组的算数运算是按照元素的. 新的数组被创建并且被结果填充

In [6]:
a = np.array([20 , 30 , 40 , 50])
b = np.arange(4)
c = a - b
d = a + b
print("数组a:" , a)
print("数组b:" , b)
print("数组c:" , c)
print("数组d:" , d)


数组a: [20 30 40 50]
数组b: [0 1 2 3]
数组c: [20 29 38 47]
数组d: [20 31 42 53]


##### 2 矩阵乘法
- 矩阵乘法可以使用 dot() 函数或 @ 运算符进行计算

In [5]:
x = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
y = np.array([[6 , 23] , [-1 , 7] , [8 , 9]])
print(x.dot(y))
print("----------------------")
print(x @ y)
print("----------------------")
print(np.dot(x , y))

[[ 28  64]
 [ 67 181]]
----------------------
[[ 28  64]
 [ 67 181]]
----------------------
[[ 28  64]
 [ 67 181]]
